[package]
name = "mumbo_lang"
version = "0.1.0"
edition = "2024"

[dependencies]
voxell_rng = "0.6.0"
voxell_timer = "1.2.2"

[profile.release]
lto = true
panic = "abort"
strip = true
codegen-units = 1

# flamegraph target
[profile.fg]
inherits = "release"
debug = true
strip = false
